import {
  Injectable,
  BadRequestException,
  NotFoundException,
  ForbiddenException,
  Logger,
} from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { AuditLoggerService } from '../../common/audit/audit-logger.service';
import * as crypto from 'crypto';

@Injectable()
export class EmergencySecurityService {
  private readonly logger = new Logger(EmergencySecurityService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly auditLogger: AuditLoggerService,
  ) {}

  /**
   * Generates or retrieves the platform emergency state.
   */
  async getPlatformSecurityState() {
    let state = await (this.prisma as any).platformSecurityState.findUnique({
      where: { id: 'global' },
    });

    if (!state) {
      state = await (this.prisma as any).platformSecurityState.create({
        data: {
          id: 'global',
          emergencyMode: false,
        },
      });
    }

    return state;
  }

  /**
   * Generates a single-use break-glass confirmation code for global platform lockdown.
   */
  async generateBreakGlassCode(actorId: string): Promise<string> {
    const code = `EMERGENCY-${crypto.randomBytes(4).toString('hex').toUpperCase()}`;
    await (this.prisma as any).platformSecurityState.upsert({
      where: { id: 'global' },
      update: { confirmationCode: code },
      create: { id: 'global', emergencyMode: false, confirmationCode: code },
    });

    this.logger.warn(`Break-glass emergency confirmation code generated by actor ${actorId}`);
    return code;
  }

  /**
   * Emergency revocation of all active sessions for a user.
   */
  async revokeUserSessions(userId: string, reason: string, actorId: string) {
    if (!reason || reason.trim().length < 10) {
      throw new BadRequestException('Emergency action requires a detailed reason of at least 10 characters');
    }

    const user = await this.prisma.user.findUnique({ where: { id: userId } });
    if (!user) {
      throw new NotFoundException(`User ${userId} not found`);
    }

    // Revoke all active sessions
    const now = new Date();
    const updateResult = await this.prisma.userSession.updateMany({
      where: {
        userId,
        revokedAt: null,
      },
      data: {
        revokedAt: now,
      },
    });

    // Write sealed audit event
    await this.auditLogger.log({
      userId: actorId,
      targetUserId: userId,
      action: 'USER_SESSIONS_EMERGENCY_REVOKED',
      module: 'Security',
      details: {
        targetUserId: userId,
        targetEmail: user.email,
        reason: reason.trim(),
        revokedSessionCount: updateResult.count,
        revokedAt: now.toISOString(),
      },
    });

    return {
      success: true,
      revokedCount: updateResult.count,
      message: `Emergency revoked ${updateResult.count} session(s) for user ${user.email}`,
    };
  }

  /**
   * Emergency locking of a user account.
   */
  async lockUser(userId: string, reason: string, confirmation: string, actorId: string) {
    if (confirmation !== 'LOCK USER') {
      throw new BadRequestException('Explicit confirmation "LOCK USER" is required');
    }
    if (!reason || reason.trim().length < 10) {
      throw new BadRequestException('Emergency action requires a detailed reason of at least 10 characters');
    }

    const user = await this.prisma.user.findUnique({ where: { id: userId } });
    if (!user) {
      throw new NotFoundException(`User ${userId} not found`);
    }

    if (user.id === actorId) {
      throw new ForbiddenException('Super Admin cannot lock their own account via emergency control');
    }

    // Idempotency: check if already locked
    if ((user as any).securityStatus === 'LOCKED') {
      return { success: true, message: `User ${user.email} is already locked` };
    }

    // Update securityStatus & revoke sessions
    const now = new Date();
    await this.prisma.$transaction(async (tx) => {
      await (tx as any).user.update({
        where: { id: userId },
        data: { securityStatus: 'LOCKED' },
      });

      await tx.userSession.updateMany({
        where: { userId, revokedAt: null },
        data: { revokedAt: now },
      });

      await this.auditLogger.log(
        {
          userId: actorId,
          targetUserId: userId,
          action: 'USER_SECURITY_LOCKED',
          module: 'Security',
          details: {
            targetUserId: userId,
            targetEmail: user.email,
            reason: reason.trim(),
            lockedAt: now.toISOString(),
          },
        },
        tx,
      );
    });

    this.logger.warn(`User ${user.email} (${userId}) LOCKED by Super Admin ${actorId}: ${reason}`);
    return { success: true, message: `User ${user.email} has been locked and all sessions revoked` };
  }

  /**
   * Emergency unlocking of a user account.
   */
  async unlockUser(userId: string, reason: string, actorId: string) {
    if (!reason || reason.trim().length < 10) {
      throw new BadRequestException('Emergency action requires a detailed reason of at least 10 characters');
    }

    const user = await this.prisma.user.findUnique({ where: { id: userId } });
    if (!user) {
      throw new NotFoundException(`User ${userId} not found`);
    }

    if ((user as any).securityStatus === 'ACTIVE') {
      return { success: true, message: `User ${user.email} is already active` };
    }

    await this.prisma.$transaction(async (tx) => {
      await (tx as any).user.update({
        where: { id: userId },
        data: { securityStatus: 'ACTIVE' },
      });

      await this.auditLogger.log(
        {
          userId: actorId,
          targetUserId: userId,
          action: 'USER_SECURITY_UNLOCKED',
          module: 'Security',
          details: {
            targetUserId: userId,
            targetEmail: user.email,
            reason: reason.trim(),
            unlockedAt: new Date().toISOString(),
          },
        },
        tx,
      );
    });

    this.logger.log(`User ${user.email} (${userId}) UNLOCKED by Super Admin ${actorId}: ${reason}`);
    return { success: true, message: `User ${user.email} has been unlocked` };
  }

  /**
   * Forces a password reset on a user account and revokes their active sessions.
   */
  async forcePasswordReset(userId: string, reason: string, actorId: string) {
    if (!reason || reason.trim().length < 5) {
      throw new BadRequestException('Reason of at least 5 characters is required');
    }

    const user = await this.prisma.user.findUnique({ where: { id: userId } });
    if (!user) {
      throw new NotFoundException(`User ${userId} not found`);
    }

    const now = new Date();
    await this.prisma.$transaction(async (tx) => {
      await (tx as any).user.update({
        where: { id: userId },
        data: { mustResetPassword: true },
      });

      await tx.userSession.updateMany({
        where: { userId, revokedAt: null },
        data: { revokedAt: now },
      });

      await this.auditLogger.log(
        {
          userId: actorId,
          targetUserId: userId,
          action: 'PASSWORD_RESET_FORCED',
          module: 'Security',
          details: {
            targetUserId: userId,
            targetEmail: user.email,
            reason: reason.trim(),
            forcedAt: now.toISOString(),
          },
        },
        tx,
      );
    });

    try {
      const { invalidateSessionCache } = require('../../auth/supabase.guard');
      invalidateSessionCache(undefined, userId);
    } catch (_) {}

    this.logger.warn(`Password reset forced for ${user.email} (${userId}) by Super Admin ${actorId}: ${reason}`);
    return {
      success: true,
      message: `Password reset has been forced for ${user.email}. All existing active sessions have been revoked.`,
    };
  }

  /**
   * Emergency lockdown of a tenant organization.
   */
  async lockTenant(tenantId: string, reason: string, confirmation: string, actorId: string) {
    if (confirmation !== 'LOCK TENANT') {
      throw new BadRequestException('Explicit confirmation "LOCK TENANT" is required');
    }
    if (!reason || reason.trim().length < 10) {
      throw new BadRequestException('Emergency action requires a detailed reason of at least 10 characters');
    }

    const tenant = await this.prisma.tenant.findUnique({ where: { id: tenantId } });
    if (!tenant) {
      throw new NotFoundException(`Tenant ${tenantId} not found`);
    }

    if ((tenant as any).securityStatus === 'LOCKED') {
      return { success: true, message: `Tenant ${tenant.name} is already locked` };
    }

    const now = new Date();
    await this.prisma.$transaction(async (tx) => {
      await (tx as any).tenant.update({
        where: { id: tenantId },
        data: { securityStatus: 'LOCKED' },
      });

      // Revoke sessions of all tenant users
      const tenantUsers = await tx.tenantUser.findMany({
        where: { tenantId },
        select: { userId: true },
      });
      const userIds = tenantUsers.map((tu) => tu.userId);

      if (userIds.length > 0) {
        await tx.userSession.updateMany({
          where: { userId: { in: userIds }, revokedAt: null },
          data: { revokedAt: now },
        });
      }

      await this.auditLogger.log(
        {
          tenantId,
          userId: actorId,
          action: 'TENANT_SECURITY_LOCKED',
          module: 'Security',
          details: {
            tenantId,
            tenantName: tenant.name,
            reason: reason.trim(),
            affectedUsersCount: userIds.length,
            lockedAt: now.toISOString(),
          },
        },
        tx,
      );
    });

    this.logger.warn(`Tenant ${tenant.name} (${tenantId}) LOCKED by Super Admin ${actorId}: ${reason}`);
    return { success: true, message: `Tenant ${tenant.name} locked and active user sessions terminated` };
  }

  /**
   * Emergency unlocking of a tenant organization.
   */
  async unlockTenant(tenantId: string, reason: string, actorId: string) {
    if (!reason || reason.trim().length < 10) {
      throw new BadRequestException('Emergency action requires a detailed reason of at least 10 characters');
    }

    const tenant = await this.prisma.tenant.findUnique({ where: { id: tenantId } });
    if (!tenant) {
      throw new NotFoundException(`Tenant ${tenantId} not found`);
    }

    if ((tenant as any).securityStatus === 'ACTIVE') {
      return { success: true, message: `Tenant ${tenant.name} is already active` };
    }

    await this.prisma.$transaction(async (tx) => {
      await (tx as any).tenant.update({
        where: { id: tenantId },
        data: { securityStatus: 'ACTIVE' },
      });

      await this.auditLogger.log(
        {
          tenantId,
          userId: actorId,
          action: 'TENANT_SECURITY_UNLOCKED',
          module: 'Security',
          details: {
            tenantId,
            tenantName: tenant.name,
            reason: reason.trim(),
            unlockedAt: new Date().toISOString(),
          },
        },
        tx,
      );
    });

    this.logger.log(`Tenant ${tenant.name} (${tenantId}) UNLOCKED by Super Admin ${actorId}: ${reason}`);
    return { success: true, message: `Tenant ${tenant.name} unlocked and CRM operations restored` };
  }

  /**
   * Global platform emergency lockdown.
   */
  async enablePlatformEmergency(
    reason: string,
    confirmation: string,
    confirmationCode: string,
    actorId: string,
  ) {
    if (confirmation !== 'ENABLE EMERGENCY MODE') {
      throw new BadRequestException('Explicit confirmation "ENABLE EMERGENCY MODE" is required');
    }
    if (!reason || reason.trim().length < 10) {
      throw new BadRequestException('Emergency action requires a detailed reason of at least 10 characters');
    }

    const state = await this.getPlatformSecurityState();
    if (state.emergencyMode) {
      return { success: true, message: 'Platform is already in emergency mode' };
    }

    if (!state.confirmationCode || state.confirmationCode !== confirmationCode.trim()) {
      throw new ForbiddenException('Invalid or expired break-glass confirmation code');
    }

    const now = new Date();
    await this.prisma.$transaction(async (tx) => {
      await (tx as any).platformSecurityState.update({
        where: { id: 'global' },
        data: {
          emergencyMode: true,
          reason: reason.trim(),
          confirmationCode: null,
          enabledAt: now,
          enabledBy: actorId,
        },
      });

      await this.auditLogger.log(
        {
          userId: actorId,
          action: 'PLATFORM_EMERGENCY_ENABLED',
          module: 'Security',
          details: {
            reason: reason.trim(),
            enabledAt: now.toISOString(),
            enabledBy: actorId,
          },
        },
        tx,
      );
    });

    this.logger.error(`[CRITICAL] PLATFORM EMERGENCY MODE ENABLED by Super Admin ${actorId}: ${reason}`);
    return { success: true, message: 'Global platform emergency mode has been enabled' };
  }

  /**
   * Disables global platform emergency mode.
   */
  async disablePlatformEmergency(reason: string, actorId: string) {
    if (!reason || reason.trim().length < 10) {
      throw new BadRequestException('Emergency action requires a detailed reason of at least 10 characters');
    }

    const state = await this.getPlatformSecurityState();
    if (!state.emergencyMode) {
      return { success: true, message: 'Platform is not in emergency mode' };
    }

    const now = new Date();
    await this.prisma.$transaction(async (tx) => {
      await (tx as any).platformSecurityState.update({
        where: { id: 'global' },
        data: {
          emergencyMode: false,
          disabledAt: now,
          disabledBy: actorId,
        },
      });

      await this.auditLogger.log(
        {
          userId: actorId,
          action: 'PLATFORM_EMERGENCY_DISABLED',
          module: 'Security',
          details: {
            reason: reason.trim(),
            disabledAt: now.toISOString(),
            disabledBy: actorId,
          },
        },
        tx,
      );
    });

    this.logger.log(`Platform emergency mode DISABLED by Super Admin ${actorId}: ${reason}`);
    return { success: true, message: 'Global platform emergency mode has been disabled' };
  }
}
