const CRM_ROLES = {
  SUPER_ADMIN: "super_admin",
  SALES_MANAGER: "sales_manager",
  SALES_EXECUTIVE: "sales_executive",
  SUPPORT_EXECUTIVE: "support_executive",
  HR_MANAGER: "hr_manager",
};

const rolePermissionConfig = {
  [CRM_ROLES.SUPER_ADMIN]: {
    roleName: "Super Admin",
    description: "Full platform owner with organization-wide control.",
    permissions: [
      "dashboard.view",
      "leads.create",
      "leads.read",
      "leads.update",
      "leads.delete",
      "customers.create",
      "customers.read",
      "customers.update",
      "customers.delete",
      "pipeline.create",
      "pipeline.read",
      "pipeline.update",
      "pipeline.delete",
      "tasks.create",
      "tasks.read",
      "tasks.update",
      "tasks.delete",
      "calendar.read",
      "quotations.create",
      "quotations.read",
      "quotations.update",
      "quotations.delete",
      "reports.read",
      "analytics.read",
      "ai.read",
      "employees.read",
      "employees.manage",
      "role_management.read",
      "role_management.manage",
      "settings.read",
      "settings.manage",
      "support_tickets.read",
      "support_tickets.manage",
      "attendance.read",
      "performance.read",
    ],
    routes: [
      "/dashboard",
      "/leads",
      "/customers",
      "/pipeline",
      "/tasks",
      "/calendar",
      "/quotations",
      "/reports",
      "/analytics",
      "/ai-insights",
      "/employees",
      "/role-management",
      "/settings",
      "/support-tickets",
      "/attendance",
      "/performance",
      "/team-performance",
    ],
    dashboardWidgets: [
      "revenue",
      "activeDeals",
      "newLeads",
      "winRate",
      "salesChart",
      "upcomingMeetings",
      "hotLeads",
      "teamPerformance",
      "leadFunnel",
      "revenueTracker",
      "recentActivities",
      "pendingFollowups",
      "aiInsights",
      "calendarWidget",
    ],
    analyticsVisibility: "full",
  },
  [CRM_ROLES.SALES_MANAGER]: {
    roleName: "Sales Manager",
    description: "Leads, pipeline, quotations, and team performance ownership.",
    permissions: [
      "dashboard.view",
      "leads.create",
      "leads.read",
      "leads.update",
      "customers.read",
      "customers.update",
      "pipeline.read",
      "pipeline.update",
      "tasks.create",
      "tasks.read",
      "tasks.update",
      "calendar.read",
      "quotations.create",
      "quotations.read",
      "quotations.update",
      "quotations.approve",
      "reports.read",
      "team_performance.read",
      "team.assign_leads",
      "team.assign_tasks",
    ],
    routes: [
      "/dashboard",
      "/leads",
      "/customers",
      "/pipeline",
      "/tasks",
      "/calendar",
      "/quotations",
      "/reports",
      "/team-performance",
    ],
    dashboardWidgets: [
      "activeDeals",
      "newLeads",
      "winRate",
      "salesChart",
      "hotLeads",
      "teamPerformance",
      "leadFunnel",
      "pendingFollowups",
      "calendarWidget",
    ],
    analyticsVisibility: "team",
  },
  [CRM_ROLES.SALES_EXECUTIVE]: {
    roleName: "Sales Executive",
    description: "Handles assigned leads and customer follow-ups.",
    permissions: [
      "dashboard.view",
      "leads.read_assigned",
      "leads.update_assigned",
      "customers.read",
      "tasks.read_assigned",
      "tasks.update_assigned",
      "calendar.read",
      "quotations.create",
      "quotations.read_assigned",
      "quotations.update_assigned",
      "followups.manage",
    ],
    routes: [
      "/dashboard",
      "/my-leads",
      "/customers",
      "/tasks",
      "/calendar",
      "/quotations",
    ],
    dashboardWidgets: [
      "newLeads",
      "upcomingMeetings",
      "pendingFollowups",
      "calendarWidget",
    ],
    analyticsVisibility: "self",
  },
  [CRM_ROLES.SUPPORT_EXECUTIVE]: {
    roleName: "Support Executive",
    description: "Owns customer support requests and communication logs.",
    permissions: [
      "dashboard.view",
      "customers.read",
      "customers.update",
      "support_tickets.read",
      "support_tickets.manage",
      "tasks.read",
      "tasks.update",
      "calendar.read",
      "communication_logs.manage",
    ],
    routes: ["/dashboard", "/customers", "/support-tickets", "/tasks", "/calendar"],
    dashboardWidgets: [
      "recentActivities",
      "pendingFollowups",
      "calendarWidget",
    ],
    analyticsVisibility: "limited",
  },
  [CRM_ROLES.HR_MANAGER]: {
    roleName: "HR Manager",
    description: "Employee lifecycle, attendance, and performance operations.",
    permissions: [
      "dashboard.view",
      "employees.read",
      "employees.manage",
      "attendance.read",
      "performance.read",
      "tasks.create",
      "tasks.read",
      "tasks.update",
      "calendar.read",
      "hr_analytics.read",
      "onboarding.manage",
    ],
    routes: [
      "/dashboard",
      "/employees",
      "/attendance",
      "/performance",
      "/tasks",
      "/calendar",
    ],
    dashboardWidgets: [
      "upcomingMeetings",
      "teamPerformance",
      "recentActivities",
      "calendarWidget",
    ],
    analyticsVisibility: "hr",
  },
};

const demoAccounts = [
  {
    email: "superadmin@clientrisecrm.com",
    password: "SuperAdmin@123",
    name: "Super Admin",
    role: CRM_ROLES.SUPER_ADMIN,
  },
  {
    email: "salesmanager@clientrisecrm.com",
    password: "SalesManager@123",
    name: "Sales Manager",
    role: CRM_ROLES.SALES_MANAGER,
  },
  {
    email: "salesexec@clientrisecrm.com",
    password: "SalesExec@123",
    name: "Sales Executive",
    role: CRM_ROLES.SALES_EXECUTIVE,
  },
  {
    email: "support@clientrisecrm.com",
    password: "Support@123",
    name: "Support Executive",
    role: CRM_ROLES.SUPPORT_EXECUTIVE,
  },
  {
    email: "hrmanager@clientrisecrm.com",
    password: "HRManager@123",
    name: "HR Manager",
    role: CRM_ROLES.HR_MANAGER,
  },
];

function getRoleAccess(role) {
  return rolePermissionConfig[role] || rolePermissionConfig[CRM_ROLES.SALES_EXECUTIVE];
}

module.exports = {
  CRM_ROLES,
  demoAccounts,
  getRoleAccess,
  rolePermissionConfig,
};
