-- AlterTable Plan with enhanced SaaS pricing, limits, and status fields
ALTER TABLE "Plan" ADD COLUMN IF NOT EXISTS "annualPriceNum" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "Plan" ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'INR';
ALTER TABLE "Plan" ADD COLUMN IF NOT EXISTS "pricingMode" TEXT NOT NULL DEFAULT 'FIXED';
ALTER TABLE "Plan" ADD COLUMN IF NOT EXISTS "maxContacts" INTEGER NOT NULL DEFAULT 1000;
ALTER TABLE "Plan" ADD COLUMN IF NOT EXISTS "maxApiRequests" INTEGER NOT NULL DEFAULT 10000;
ALTER TABLE "Plan" ADD COLUMN IF NOT EXISTS "trialDays" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Plan" ADD COLUMN IF NOT EXISTS "billingCycleMonthly" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Plan" ADD COLUMN IF NOT EXISTS "billingCycleAnnual" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Plan" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE "Plan" ADD COLUMN IF NOT EXISTS "sortOrder" INTEGER NOT NULL DEFAULT 0;

-- CreateIndex
CREATE INDEX IF NOT EXISTS "Plan_status_idx" ON "Plan"("status");
CREATE INDEX IF NOT EXISTS "Plan_sortOrder_idx" ON "Plan"("sortOrder");
